---
  mcu: "rp2040"
  usb: true
  uart:
    dinMIDI:
      pins:
        rx:
          port: "0"
          index: 1
        tx:
          port: "0"
          index: 0
    touchscreen:
      pins:
        rx:
          port: "0"
          index: 5
        tx:
          port: "0"
          index: 4
      components: 64
  i2c:
    display:
      pins:
        sda:
          port: "0"
          index: 16
        scl:
          port: "0"
          index: 17
  buttons:
    type: "shiftRegister"
    shiftRegisters: 4
    encoders: false
    pins:
      data:
        port: "0"
        index: 6
      clock:
        port: "0"
        index: 7
      latch:
        port: "0"
        index: 8
    indexing:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 24
    - 25
    - 26
    - 27
    - 28
    - 29
    - 30
    - 31
  analog:
    type: "4051"
    inputVoltage: "3.3"
    multiplexers: 1
    pins:
      s0:
        port: "0"
        index: 9
      s1:
        port: "0"
        index: 10
      s2:
        port: "0"
        index: 11
      z0:
        port: "0"
        index: 26
  leds:
    internal:
      invert: false
      pins:
        usb:
          rx:
            port: "0"
            index: 12
          tx:
            port: "0"
            index: 13
    external:
      type: "native"
      pins:
      -
        port: "0"
        index: 14
      -
        port: "0"
        index: 15
      -
        port: "0"
        index: 22
      -
        port: "0"
        index: 21
      -
        port: "0"
        index: 20
      -
        port: "0"
        index: 19
      -
        port: "0"
        index: 18
  saxophone:
    registerChromatic: true
  test: true